/**
 * @fileoverview Tests for config/context-file-generator module.
 *
 * Validates that GEMINI.md and AGENTS.md are correctly derived from
 * CLAUDE.md content with appropriate text replacements, section stripping,
 * and auto-generated headers.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { generateGeminiMd, generateAgentsMd } from '../../src/config/context-file-generator.js';

// Sample CLAUDE.md content that exercises all replacement paths
const SAMPLE_CLAUDE_MD = [
  '# MyProject',
  '',
  '## Project Context',
  '- **IDE**: Claude Code recommended',
  '- **Config**: CLAUDE.md for project context',
  '- **Local**: CLAUDE.local.md for runtime state',
  '- **Commands**: stored in .claude/commands/',
  '- **Rules**: loaded from .claude/rules/chati/',
  '- **MCP config**: .claude/mcp.json',
  '',
  '## How to Run',
  'Use `claude --print` or `claude -p` to run non-interactively.',
  '',
  '## Hooks',
  'The framework uses 6 hooks for governance:',
  '- mode-governance',
  '- constitution-guard',
  '- **Hooks**: 6 Claude Code hooks active',
  '',
  '## Hook System',
  'Hooks intercept events and enforce rules.',
  'They run before and after agent execution.',
  '',
  '## Chati.dev',
  'Type `/chati` to start.',
  '',
  '## Pipeline',
  'DISCOVER -> PLAN -> BUILD -> DEPLOY',
  '',
  '---',
  '_Auto-updated by chati.dev_',
].join('\n');

// ---------------------------------------------------------------------------
// generateGeminiMd
// ---------------------------------------------------------------------------

describe('generateGeminiMd', () => {
  it('replaces Claude Code with Gemini CLI', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('Claude Code'), 'Should not contain "Claude Code"');
    assert.ok(result.includes('Gemini CLI'), 'Should contain "Gemini CLI"');
  });

  it('replaces CLAUDE.md with GEMINI.md', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    // The header legitimately contains "from CLAUDE.md" — strip it before checking
    const body = result.replace(/^<!--.*-->\n\n?/, '');
    assert.ok(!body.includes('CLAUDE.md'), 'Body should not contain "CLAUDE.md"');
    assert.ok(body.includes('GEMINI.md'), 'Body should contain "GEMINI.md"');
  });

  it('replaces .claude/commands/ with .gemini/commands/', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/commands/'), 'Should not contain ".claude/commands/"');
    assert.ok(result.includes('.gemini/commands/'), 'Should contain ".gemini/commands/"');
  });

  it('adds auto-generated header', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.startsWith('<!-- Auto-generated by chati.dev from CLAUDE.md'));
    assert.ok(result.includes('do not edit manually'));
  });

  it('replaces .claude/rules/ with .gemini/context/', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/rules/'), 'Should not contain ".claude/rules/"');
    assert.ok(result.includes('.gemini/context/'), 'Should contain ".gemini/context/"');
  });

  it('replaces .claude/mcp.json with .gemini/settings.json', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/mcp.json'), 'Should not contain ".claude/mcp.json"');
    assert.ok(result.includes('.gemini/settings.json'), 'Should contain ".gemini/settings.json"');
  });

  it('replaces claude --print with gemini --prompt', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('claude --print'), 'Should not contain "claude --print"');
    assert.ok(result.includes('gemini --prompt'), 'Should contain "gemini --prompt"');
  });

  it('replaces CLAUDE.local.md with .gemini/session-lock.md', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('CLAUDE.local.md'), 'Should not contain "CLAUDE.local.md"');
    assert.ok(result.includes('.gemini/session-lock.md'), 'Should contain ".gemini/session-lock.md"');
  });

  it('preserves non-replaced content', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.includes('# MyProject'));
    assert.ok(result.includes('## Pipeline'));
    assert.ok(result.includes('DISCOVER -> PLAN -> BUILD -> DEPLOY'));
  });

  // --- @import directives (context parity) ---

  it('includes 5 @import directives', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    const imports = result.match(/@import /g);
    assert.equal(imports.length, 5, 'Should have 5 @import directives');
  });

  it('@imports include .gemini/context/ files', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.includes('@import .gemini/context/root.md'));
    assert.ok(result.includes('@import .gemini/context/governance.md'));
    assert.ok(result.includes('@import .gemini/context/protocols.md'));
    assert.ok(result.includes('@import .gemini/context/quality.md'));
  });

  it('@imports include .gemini/session-lock.md', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.includes('@import .gemini/session-lock.md'));
  });

  it('@import directives are at the end of the file', () => {
    const result = generateGeminiMd(SAMPLE_CLAUDE_MD);
    const lines = result.trim().split('\n');
    const lastLines = lines.slice(-5);
    for (const line of lastLines) {
      assert.ok(line.startsWith('@import '), `Last lines should be @import: "${line}"`);
    }
  });
});

// ---------------------------------------------------------------------------
// generateAgentsMd
// ---------------------------------------------------------------------------

describe('generateAgentsMd', () => {
  it('replaces Claude Code with Codex CLI', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('Claude Code'), 'Should not contain "Claude Code"');
    assert.ok(result.includes('Codex CLI'), 'Should contain "Codex CLI"');
  });

  it('replaces CLAUDE.md with AGENTS.md', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    // The header legitimately contains "from CLAUDE.md" — strip it before checking
    const body = result.replace(/^<!--.*-->\n\n?/, '');
    assert.ok(!body.includes('CLAUDE.md'), 'Body should not contain "CLAUDE.md"');
    assert.ok(body.includes('AGENTS.md'), 'Body should contain "AGENTS.md"');
  });

  it('strips hook-related sections', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    // The ## Hooks and ## Hook System sections should be stripped
    assert.ok(!result.includes('## Hooks'), 'Should not contain "## Hooks" section');
    assert.ok(!result.includes('## Hook System'), 'Should not contain "## Hook System" section');
  });

  it('strips inline hook references', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    // "- **Hooks**: 6 Claude Code hooks active" should be stripped
    assert.ok(!result.includes('6 hooks'), 'Should strip hook bullet lines');
  });

  it('adds auto-generated header', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.startsWith('<!-- Auto-generated by chati.dev from CLAUDE.md'));
    assert.ok(result.includes('do not edit manually'));
  });

  it('replaces .claude/commands/ with chati.dev/orchestrator/ (Codex has no commands/)', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/commands/'), 'Should not contain ".claude/commands/"');
    assert.ok(result.includes('chati.dev/orchestrator/'), 'Should contain "chati.dev/orchestrator/"');
  });

  it('replaces .claude/rules/ with chati.dev/context/ (Codex has no rules/)', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/rules/'), 'Should not contain ".claude/rules/"');
    assert.ok(result.includes('chati.dev/context/'), 'Should contain "chati.dev/context/"');
  });

  it('replaces claude --print with codex exec', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('claude --print'), 'Should not contain "claude --print"');
    assert.ok(result.includes('codex exec'), 'Should contain "codex exec"');
  });

  it('replaces CLAUDE.local.md with AGENTS.override.md', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('CLAUDE.local.md'), 'Should not contain "CLAUDE.local.md"');
    assert.ok(result.includes('AGENTS.override.md'), 'Should contain "AGENTS.override.md"');
  });

  it('replaces .claude/mcp.json with .codex/config.toml', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('.claude/mcp.json'), 'Should not contain ".claude/mcp.json"');
    assert.ok(result.includes('.codex/config.toml'), 'Should contain ".codex/config.toml"');
  });

  it('does not leave triple blank lines after stripping', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('\n\n\n'), 'Should not have 3+ consecutive newlines');
  });

  it('converts /chati to $chati (Codex uses $ for skill invocation)', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.includes('$chati'), 'Should convert /chati to $chati for Codex');
    assert.ok(!result.includes('/chati'), 'Should not preserve /chati in Codex context');
  });

  it('preserves non-replaced, non-hook content', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(result.includes('# MyProject'));
    assert.ok(result.includes('## Pipeline'));
    assert.ok(result.includes('DISCOVER -> PLAN -> BUILD -> DEPLOY'));
  });
});

// ---------------------------------------------------------------------------
// generateAgentsMd with inline contextFiles
// ---------------------------------------------------------------------------

describe('generateAgentsMd with inline contextFiles', () => {
  const SAMPLE_CONTEXT_FILES = {
    root: '# System Context\n## Framework\n- **Version**: 3.0.0\n- References CLAUDE.md for context',
    governance: '# Governance Rules\n## Mode Governance\n- planning: write to chati.dev/ only\n- Claude Code processes',
    protocols: '# Protocols\n## Self-Validation\nEvery agent validates output\n## CLAUDE.local.md references',
    quality: '# Quality Standards\n## Gate Thresholds\n- qa-planning: 95%',
  };

  it('includes governance content when contextFiles provided', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD, SAMPLE_CONTEXT_FILES);
    assert.ok(result.includes('Governance Rules'), 'Should include governance content');
    assert.ok(result.includes('Mode Governance'), 'Should include mode governance details');
  });

  it('includes protocols content when contextFiles provided', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD, SAMPLE_CONTEXT_FILES);
    assert.ok(result.includes('Protocols'), 'Should include protocols');
    assert.ok(result.includes('Self-Validation'), 'Should include self-validation protocol');
  });

  it('includes quality content when contextFiles provided', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD, SAMPLE_CONTEXT_FILES);
    assert.ok(result.includes('Quality Standards'), 'Should include quality');
    assert.ok(result.includes('95%'), 'Should include threshold values');
  });

  it('adapts inline context for Codex (replaces Claude refs)', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD, SAMPLE_CONTEXT_FILES);
    assert.ok(!result.includes('Claude Code processes'), 'Should replace Claude Code refs in inline context');
    assert.ok(result.includes('Codex CLI'), 'Should contain Codex CLI in inline context');
  });

  it('replaces CLAUDE.md refs in inline context', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD, SAMPLE_CONTEXT_FILES);
    // After the auto-generated header comment, no CLAUDE.md refs should remain in body
    const afterHeader = result.replace(/^<!--.*-->\n\n?/, '');
    assert.ok(!afterHeader.includes('CLAUDE.md'), 'Inline context should not reference CLAUDE.md');
  });

  it('replaces CLAUDE.local.md refs in inline context', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD, SAMPLE_CONTEXT_FILES);
    assert.ok(!result.includes('CLAUDE.local.md'), 'Inline context should not reference CLAUDE.local.md');
  });

  it('separates inline sections with ---', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD, SAMPLE_CONTEXT_FILES);
    assert.ok(result.includes('---'), 'Should have --- separators for inline sections');
  });

  it('total output is under 32 KiB (Codex limit)', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD, SAMPLE_CONTEXT_FILES);
    const sizeKiB = Buffer.byteLength(result, 'utf-8') / 1024;
    assert.ok(sizeKiB < 32, `Output should be under 32 KiB, got ${sizeKiB.toFixed(1)} KiB`);
  });

  it('backward compat: no contextFiles = no inline sections', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.ok(!result.includes('Governance Rules'), 'Without contextFiles, should not have inline governance');
    assert.ok(!result.includes('Quality Standards'), 'Without contextFiles, should not have inline quality');
  });

  it('null contextFiles = backward compat', () => {
    const result = generateAgentsMd(SAMPLE_CLAUDE_MD, null);
    const resultNoArg = generateAgentsMd(SAMPLE_CLAUDE_MD);
    assert.equal(result, resultNoArg, 'null contextFiles should produce same output as no argument');
  });
});
